declare module 'react-native-vector-icons/MaterialIcons';
declare module 'react-native-vector-icons/FontAwesome';
declare module 'react-native-vector-icons/AntDesign';
declare module 'react-native-vector-icons/Entypo';
declare module 'react-native-vector-icons/Fontisto';
declare module 'react-native-star-view';
declare module 'react-native-progress/Bar';
declare module 'react-native-vector-icons/MaterialCommunityIcons';
declare module 'react-native-vector-icons/Feather'